info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Go Starter API
  termsOfService: http://swagger.io/terms/
  title: Go Starter API
  version: 0.0.1
paths: {}
swagger: "2.0"
